FROM node:20-bookworm-slim AS build

ARG SERVER_HOST=sim.example.com
ARG CLIENT_HOST=play.example.com
ARG REPLAY_HOST=replay.example.com
WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends git python3 make g++ ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci

COPY . .

COPY --from=showdown-server package*.json ./caches/pokemon-showdown/
RUN cd caches/pokemon-showdown && npm ci && cd ../..
COPY --from=showdown-server . ./caches/pokemon-showdown/
RUN cd caches/pokemon-showdown && node build && cd ../..

# Publish the fork-owned pkmn/randbats-compatible feed. The server repo owns
# generation and schema validation; the client serves the committed artifacts
# same-origin for native tooltips and the embedded standalone Showdex.
RUN mkdir -p play.pokemonshowdown.com/randbats/data \
    && cp -r caches/pokemon-showdown/data/random-battles/gen3mega/generated/. \
        play.pokemonshowdown.com/randbats/data/

RUN cat > config/config.js <<EOF
var Config = Config || {};
Config.version = "0";
Config.defaultserver = {
  id: 'showdown',
  host: '${SERVER_HOST}',
  port: 443,
  httpport: 80,
  altport: 80,
  registered: true
};
Config.customcolors = {};
Config.bannedHosts = [];
Config.whitelist = [];
EOF

# Upstream's Preact refactor renamed the classic testclient.html to
# testclient-old.html. The offline finalizer derives the self-hosted production
# shell from it without mutating the upstream entrypoint.
RUN node build full
RUN find play.pokemonshowdown.com -type l -exec sh -c \
    'target=$(readlink -f "$1") && rm "$1" && cp "$target" "$1"' _ {} \;
RUN echo "Config.routes.client = '${CLIENT_HOST}';" >> play.pokemonshowdown.com/config/config.js
# Self-hosted replay host: where the in-battle loadReplay() fetches {id}.json and
# where the Download/Upload-and-share replay buttons point (default route is
# replay.pokemonshowdown.com, which our deployment never reaches).
RUN echo "Config.routes.replays = '${REPLAY_HOST}';" >> play.pokemonshowdown.com/config/config.js

# Publish the standalone replay player's compiled bundles (built just above by
# `node build full` into replay.pokemonshowdown.com/js) under the play vhost at
# /replays-js/. The replay-viewer's HTML shell loads them from here, so its image
# needs no gitignored build artifacts. The bare `cp *.js` fails the build loudly
# if the bundles are ever missing instead of silently shipping a blank viewer.
RUN mkdir -p play.pokemonshowdown.com/replays-js \
    && cp replay.pokemonshowdown.com/js/*.js play.pokemonshowdown.com/replays-js/
RUN cp replay.pokemonshowdown.com/js/*.js.map play.pokemonshowdown.com/replays-js/ 2>/dev/null || true

# Bake in the Spaceworld '97 (gen2sw97) beta sprites — every demo species, so the 36
# cut designs (num >= 5000, absent from the CDN) AND real species redesigned after 1997
# (Umbreon = "Blacky", Espeon = "Eifie", ...) render their beta art. The front/back/shiny
# PNGs are committed under custom-sprites/ (regenerated by build-tools/sw97-sprites.js)
# and copied into a mod-scoped sprites/gen2sw97/ tree so standard [Gen 2] is untouched.
# nginx serves it local-first, stripping the segment to fall back to the official gen2
# sprite on a miss (docker/nginx-client.conf).
RUN mkdir -p play.pokemonshowdown.com/sprites/gen2sw97 \
    && cp -r custom-sprites/gen2sw97/. play.pokemonshowdown.com/sprites/gen2sw97/

# Generate the final precache only after the deployed HTML and runtime config
# have their production contents. Strict mode keeps a missing local dependency
# from turning into a silently incomplete offline install.
RUN npm run --silent offline:finalize -- --strict

FROM nginxinc/nginx-unprivileged:alpine
COPY docker/nginx-client.conf /etc/nginx/conf.d/default.conf
COPY docker/nginx-offline.inc /etc/nginx/conf.d/offline.inc
COPY --from=build /app/play.pokemonshowdown.com /usr/share/nginx/html
EXPOSE 8080
