import fs from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

import { OFFLINE_FORMATS_PATH, WEB_ROOT_NAME, writeIfChanged } from './policy';

export interface FormatDefinition {
	name?: string;
	section?: string;
	column?: number;
	team?: unknown;
	searchShow?: boolean;
	challengeShow?: boolean;
	tournamentShow?: boolean;
	bestOfDefault?: boolean;
	teraPreviewDefault?: boolean;
	itemClauseDefault?: boolean;
}

export interface FormatRuleTable {
	adjustLevel?: number;
	adjustLevelDown?: number;
	maxLevel?: number;
}

export interface DexLike {
	formats: {
		all(): readonly FormatDefinition[],
		getRuleTable(format: FormatDefinition): FormatRuleTable,
	};
}

export type FormatGenerationResult = {
	skipped: true,
	reason: string,
} | {
	skipped: false,
	tokens: string[],
	destination: string,
};

export const DEFAULT_FORMATS_LIST_PREFIX = '|,LL';
const requireModule = createRequire(__filename);

function prefixTokens(prefix: string): string[] {
	return prefix ? prefix.split('|').filter(Boolean) : [];
}

export function buildFormatTokens(Dex: DexLike, formatsListPrefix = DEFAULT_FORMATS_LIST_PREFIX): string[] {
	const tokens = ['formats', ...prefixTokens(formatsListPrefix)];
	let section = '';
	let previousSection = '';
	let currentColumn = 1;

	for (const format of Dex.formats.all()) {
		if (format.section) section = format.section;
		if (format.column) currentColumn = format.column;
		if (!format.name) continue;
		if (!format.challengeShow && !format.searchShow && !format.tournamentShow) continue;

		if (section !== previousSection) {
			previousSection = section;
			tokens.push(`,${currentColumn}`, section);
		}

		let displayCode = 0;
		if (format.team) displayCode |= 1;
		if (format.searchShow) displayCode |= 2;
		if (format.challengeShow) displayCode |= 4;
		if (format.tournamentShow) displayCode |= 8;
		const ruleTable = Dex.formats.getRuleTable(format);
		const level = ruleTable.adjustLevel || ruleTable.adjustLevelDown || ruleTable.maxLevel;
		if (level === 50) displayCode |= 16;
		if (format.bestOfDefault) displayCode |= 64;
		if (format.teraPreviewDefault) displayCode |= 128;
		if (format.itemClauseDefault) displayCode |= 256;
		tokens.push(`${format.name},${displayCode.toString(16)}`);
	}

	return tokens;
}

export function renderOfflineFormats(tokens: readonly string[]): string {
	const protocol = '|' + tokens.join('|');
	return `// Generated by the strict offline finalizer. Do not edit this file directly.\n` +
		`globalThis.OfflineFormats = {protocol: ${JSON.stringify(protocol)}, formats: ${JSON.stringify(tokens)}};\n` +
		`globalThis.OfflineBattleFormats = globalThis.OfflineFormats.formats;\n`;
}

export function generateOfflineFormats(
	rootDir: string,
	strict: boolean,
	formatsListPrefix = DEFAULT_FORMATS_LIST_PREFIX
): FormatGenerationResult {
	const dexPath = path.join(rootDir, 'caches', 'pokemon-showdown', 'dist', 'sim', 'dex.js');
	if (!fs.existsSync(dexPath)) {
		if (strict) throw new Error(`Server build missing: ${dexPath}`);
		return { skipped: true, reason: 'server build is unavailable' };
	}

	let Dex: DexLike;
	try {
		({ Dex } = requireModule(dexPath) as { Dex: DexLike });
	} catch (error) {
		if (strict) throw error;
		return { skipped: true, reason: 'server formats could not be loaded' };
	}
	const tokens = buildFormatTokens(Dex, formatsListPrefix);
	if (tokens.length < 2) throw new Error('The generated offline format catalog is empty.');

	const destination = path.join(rootDir, WEB_ROOT_NAME, OFFLINE_FORMATS_PATH);
	writeIfChanged(destination, renderOfflineFormats(tokens));
	return { skipped: false, tokens, destination };
}
